### ISSUE TITLE
Bug: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by bholagabbar** [synapsecns/sdk#106]
Reported by a user on the API chat here: https://github.com/synapsecns/synapse-api/issues/39#issuecomment-1100926160

Here is a gist that results in the SDK call failing: 

```
import {Bridge, Tokens} from "@synapseprotocol/sdk";
import {BigNumber} from "ethers";

const bridge = new Bridge.SynapseBridge({
    network: 56,
});

const estimate = await bridge.estimateBridgeTokenOutput({
    tokenFrom: Tokens.BUSD,
    tokenTo: Tokens.DAI,
    chainIdTo: 137,
    amountFrom: BigNumber.from("10"),
});
const unsignedTxn = await bridge.buildBridgeTokenTransaction({
    tokenFrom: Tokens.BUSD,
    chainIdTo: 137,
    tokenTo: Tokens.DAI,
    amountFrom: BigNumber.from("10"),
    amountTo: estimate.amountToReceive,
    addressTo: 0xb1a7863f407e992a5153a54b5d572e00b9b19104
})

console.log(unsignedTxn)
```

> TypeError: Cannot read property 'error' of undefined
>     at file:///synapse-api/node_modules/@synapseprotocol/sdk/dist/internal/minirpc.js:188:41
>     at Array.forEach (<anonymous>)
>     at file:///synapse-api/node_modules/@synapseprotocol/sdk/dist/internal/minirpc.js:186:45
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 

@bleaker0x

**Comment by bleaker0x** [comment]
@metagabbar Install @synapseprotocol/sdk@0.95-beta.9 and let me know if that fixes the issue.

**Comment by bholagabbar** [comment]
> @metagabbar Install @synapseprotocol/sdk@0.95-beta.9 and let me know if that fixes the issue.

@bleaker0x  Still get the following error:

```
synapse-api/testMethod.js
/synapse-api/node_modules/@ethersproject/logger/lib/index.js:199
        var error = new Error(message);
                    ^

Error: invalid address or ENS name (argument="name", value=1.0142272854538061e+48, code=INVALID_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (/synapse-api/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (synapse-api/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at Logger.throwArgumentError (synapse-api/node_modules/@ethersproject/logger/lib/index.js:211:21)
    at /synapse-api/node_modules/@ethersproject/contracts/lib/index.js:93:32
    at step (synapse-api/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (synapse-api/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/synapse-api/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'invalid address or ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: 1.0142272854538061e+48
}


```

**Comment by bleaker0x** [comment]
@metagabbar It looks like you might be passing an address as an actual hex integer value. Check and see if the address is wrapped in quotes (single or double).

It could also be something on my end, drop a link or gist to the file you're working with so I can take a look at what's being called and debug on my end as well

**Comment by bholagabbar** [comment]
> @metagabbar It looks like you might be passing an address as an actual hex integer value. Check and see if the address is wrapped in quotes (single or double).
> 
> It could also be something on my end, drop a link or gist to the file you're working with so I can take a look at what's being called and debug on my end as well

@bleaker0x  Yeah, I think those args were wrong to return that error, but on fixing them the SDK still returns
```
{
    "error": "TypeError: Cannot read properties of undefined (reading 'toString')"
}
```

Were you able to run the gist I pasted in the first comment of this issue ? You should be able to reproduce the error:
https://github.com/synapsecns/sdk/issues/106#issue-1206610386

**Comment by bleaker0x** [comment]
@metagabbar Just ran that as a test case; `toString()` doesn't seem to be being called anywhere that I can see, and the test ran fine. I'll dig a bit further, but what would also be super helpful for me is if you could try/catch that error and log its `.cause` and `.stack` properties + paste them here so I can see where the error is ultimately coming from when you're running that snippet. 

Edit to add: humour me and try/catch the `console.log` too. I have a thought which might be dumb but it's still worth it to check.

**Comment by bholagabbar** [comment]
> @metagabbar It looks like you might be passing an address as an actual hex integer value. Check and see if the address is wrapped in quotes (single or double).
> 
> It could also be something on my end, drop a link or gist to the file you're working with so I can take a look at what's being called and debug on my end as well

Thanks @bleaker0x , investigated and it was a parsing issue on my end. Seems like certain fields are intermittently being sent/not sent. 

For eg, `gasPrice` is sometimes sent as part of the response for `buildBridgeTokenTransaction` and sometimes not. I've removed the guarantees for this and 2 other fields (`gasPriceLimit` and `chainId`) on the API.
