### ISSUE TITLE
Unique symbols for tokens

### ISSUE THREAD

**Issue by bholagabbar** [synapsecns/sdk#111]
W_ETH(https://github.com/synapsecns/sdk/blob/master/src/tokens.ts#L159), WETH for Fantom(https://github.com/synapsecns/sdk/blob/master/src/tokens.ts#L210), WETH for Moonbeam(https://github.com/synapsecns/sdk/blob/master/src/tokens.ts#L172) have the same symbol WETH. The Wrapped Ether token for Avalanche is `WETH_E` with no indication it's avalanche other than it's addresses array

More dangeriously, DFK_USDC (https://github.com/synapsecns/sdk/blob/dev/src/tokens.ts#L316)and USDC(https://github.com/synapsecns/sdk/blob/master/src/tokens.ts#L42) have the same symbol!

This tends to create issues with the API and doesn't provide any unique identifier for tokens other than the hash of the BaseToken itself

**Comment by bleaker0x** [comment]
With a few exceptions, I try to keep the `symbol` field of tokens populated with the result of the `.symbol()` contract call. It's not super helpful as a unique identifier in general; one example is UST: there are several UST wrappers which are used almost interchangeably by the Terra bridge, all of which have the symbol "UST". 

Your point about having a unique identifier available is well taken, though. In terms of your usage of such a field within the API, does it matter to you whether or not the unique ID is human-readable as well as unique, or just that it's unique? No matter what, I'll most likely generate and hard-code ids to provide consistency.

**Comment by bholagabbar** [comment]
Right now, all the `BaseToken` keys, eg `DFK_USDC` are acting as the unique identifier for the token so I've been able to work my way around this in the API. 

*Ideally* something that is human readable and unique, like what you're using above would be best. I think it's worth thinking about what id/hash would be natural to a multi chain token.

**Comment by bleaker0x** [comment]
@metagabbar do you think it makes sense to have a unique ID per-chain? For example, `nETH` would have a "prefix" of `"neth"` and a suffix per-chain? Ie. "`neth_AVAX`", "neth_BOBA"`, etc. 

> The Wrapped Ether token for Avalanche is WETH_E with no indication it's avalanche other than it's addresses array

To this point, do you have any suggestions for how to address this from a code perspective? I can (and should, and plan to) considerably improve JS/TSDoc for tokens, but are there any helper properties/methods that could be exposed?

**Comment by bholagabbar** [comment]
> @metagabbar do you think it makes sense to have a unique ID per-chain? For example, `nETH` would have a "prefix" of `"neth"` and a suffix per-chain? Ie. "`neth_AVAX`", "neth_BOBA"`, etc.
> 
> > The Wrapped Ether token for Avalanche is WETH_E with no indication it's avalanche other than it's addresses array
> 
> To this point, do you have any suggestions for how to address this from a code perspective? I can (and should, and plan to) considerably improve JS/TSDoc for tokens, but are there any helper properties/methods that could be exposed?

I think this is a decent approach, but it somehow doesn't sit well with me because we're effectively augmenting the object with an attribute which has redundant data. We know the token symbol, and we know the chains it's available on and you already mentioned that you're effectively naming the symbol token the same as the `.symbol() contract call`

I was thinking something more id-ish, like a dumb but working solution would be to have a hash of `JSON.stringify(Tokens[Tokens.AVAX])` or something like that. Thoughts ?

**Comment by bleaker0x** [comment]
> like a dumb but working solution would be to have a hash of JSON.stringify(Tokens[Tokens.AVAX])

I don't _like_ this but it might be the best immediate option, and I can't think of anything better.

**Comment by bleaker0x** [comment]
@metagabbar Install `@synapseprotocol/sdk@0.95.1-alpha.12`. With commit 28846fc6db39bb0cba1a0009d7f9cbac880261f5, the `Token` interface now has a `hash` property which is -- for now? -- calculated at object initialization time by taking the MD5 sum of a few key properties of the token object. 

Going to leave this issue open for now, but please let me know if the above solution works for you.

**Comment by bholagabbar** [comment]
> @metagabbar Install `@synapseprotocol/sdk@0.95.1-alpha.12`. With commit [28846fc](https://github.com/synapsecns/sdk/commit/28846fc6db39bb0cba1a0009d7f9cbac880261f5), the `Token` interface now has a `hash` property which is -- for now? -- calculated at object initialization time by taking the MD5 sum of a few key properties of the token object.
> 
> Going to leave this issue open for now, but please let me know if the above solution works for you.

Yes, `_hash` property lgtm. Focusing on indexer project right now, so I'm not going to migrate the API to use this attribute just yet, but this is a much needed addition. WIll get back when I integrate it! Feel free to close out tho

**Comment by bholagabbar** [comment]
@bleaker0x unrelated, but if you can take a look at support channel #ticket-01003 on discord and see if there's something you can /contribute would be great
