### ISSUE TITLE
cronos new pool

### ISSUE THREAD

**Issue by BlazeWasHere** [synapsecns/sdk#112]
new nusd/usdc pool https://github.com/synapsecns/synapse-contracts/pull/127/commits/8749aadf92ab8dda438d13a35739e29aea8e8c69
new zap https://github.com/synapsecns/synapse-contracts/pull/127/commits/3bd41c7682bdd53f6c3ca6d79676a2df64cee894

@bleaker0x  need to update addresses for #104

**Comment by bleaker0x** [comment]
Added in dev and release branch :+1:
