### ISSUE TITLE
Add support for Cronos, Metis (New Chains), and Optimism gOHM

### ISSUE THREAD

**Issue by aureliusbtc** [synapsecns/sdk#48]
See: https://github.com/synapsecns/synapse-contracts/pull/82

gOHM Addresses: https://github.com/synapsecns/synapse-contracts/pull/82/commits/5b84ec78f6bebd95f80148b45a0c42a578ae91f8

**Comment by bleaker0x** [comment]
In `dev` as of #52, pushed to master as of #53 and published on NPM with https://github.com/synapsecns/sdk/releases/tag/v0.88.0.
