### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by dlpigpen** [synapsecns/sdk#92]
I got this issue with the synapse protocol version v93. Node version v1.14.18.1

```
../node_modules/@synapseprotocol/sdk/dist/index.js
require() of ES modules is not supported.

Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ../node_modules/@synapseprotocol/sdk/package.json.

```

**Comment by bleaker0x** [comment]
Hey @dlpigpen, can you try using NodeJS v16 (preferably the latest Gallium LTS, v16.4.2) or v17? 

We only test and guarantee compatibility with those version ranges; see the [wiki page](https://github.com/synapsecns/sdk/wiki/Getting%20Started%3A-FAQ#im-encountering-some-random-error) for details.
